package com.example.account.service;

import com.example.account.dto.AccountRequest;
import com.example.account.dto.AccountResponse;
import com.example.account.entity.Account;
import com.example.account.exception.AccountAlreadyExistsException;
import com.example.account.repository.AccountRepository;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;

@Service
public class AccountService {

    private final AccountRepository accountRepository;

    public AccountService(AccountRepository accountRepository) {
        this.accountRepository = accountRepository;
    }

    @Transactional
    public AccountResponse createAccount(AccountRequest request) {

        if (accountRepository.existsByAccountNumber(request.getAccountNumber())) {

            throw new AccountAlreadyExistsException("Account already exists: " + request.getAccountNumber());
        }

        Account account = new Account();

        account.setAccountNumber(request.getAccountNumber());
        account.setOwnerType(request.getOwnerType());
        account.setOwnerRefId(request.getOwnerRefId());
        account.setIfsc(request.getIfsc());
        account.setAccountType(request.getAccountType());

        // These values are generated by the system
        account.setStatus("ACTIVE");
        account.setAvailableBalance(BigDecimal.ZERO);
        account.setLedgerBalance(BigDecimal.ZERO);

        Account savedAccount = accountRepository.save(account);

        return new AccountResponse(
                savedAccount.getAccountNumber(),
                savedAccount.getOwnerType(),
                savedAccount.getOwnerRefId(),
                savedAccount.getIfsc(),
                savedAccount.getAccountType(),
                savedAccount.getStatus(),
                savedAccount.getAvailableBalance(),
                savedAccount.getLedgerBalance()
        );
    }
    @Transactional(readOnly = true)
    public AccountResponse getBalance(String accountNumber) {

        Account account = accountRepository.findByAccountNumber(accountNumber)
                .orElseThrow(() -> new RuntimeException("Account not found: " + accountNumber));

        return new AccountResponse(
                account.getAccountNumber(),
                account.getOwnerType(),
                account.getOwnerRefId(),
                account.getIfsc(),
                account.getAccountType(),
                account.getStatus(),
                account.getAvailableBalance(),
                account.getLedgerBalance()
        );
    }
}